- name: Run the equivalent of "apt-get update"
  become: true
  apt:
    update_cache: yes

- name: Enable cgroups
  become: true
  command:
    cmd: sed -i '${s/$/ cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1/}' /boot/firmware/cmdline.txt
    warn: false

- name: Reboot the machine after cgroups enablement
  become: yes
  reboot:
    msg: "Ansible: rebooting after cgroups enablement"

- name: Install microk8s
  become: yes
  community.general.snap:
    name: microk8s
    classic: yes

- name: Waiting for microk8s to be ready
  become: true
  command: sh -xc "export LC_ALL=C.UTF-8 && microk8s.status --wait-ready"

- name: Enable microk8s DNS and storage
  become: true
  command: sh -xc "export LC_ALL=C.UTF-8 && microk8s.enable dns storage"
